server:
  port: 9192
spring:
  application:
    name: Microservice Secure Platform Solutions
  data:
    mongodb:
      database: secure-platform-solutions
      port: 27017
      host: localhost
  profiles:
    actives: prod, dev, qa
info:
  app:
    name: Secure Platform Solutions Microservice
    version: 1.0
    decription: CRUD Users | Solutions | Profiles | Activities Microservice


